[package]
name = "timeshards-client"
version.workspace = true
edition.workspace = true
description = "AI TimeShards desktop client"

[lib]
name = "timeshards_client_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
