[package]
name = "timeshards-kernel"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
timeshards-core = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
